server:
  port: 5011
  host: localhost

database:
  host: localhost
  port: 5432
  username: postgres
  password: 1
  tablename: acfun_comm

logger:
  level: "debug"
  onSave: false
  path: "./logs/runlog.log"
  maxSize: 10 # 单个日志最大体积MB
  maxBackups: 10 # 最大日志文件数量
  maxAge: 7 # 保留天数

proxyServer:
  port: 5010
  host: localhost

spiders:
  - type: "comments"
    prefix: "comments-spider-"
    spec: 2
  - type: "articles"
    prefix: "articles-spider-"
    spec: 1

articlesRequestUrl: "https://www.acfun.cn/rest/pc-direct/article/feed"

articleUrl:
  - referer: "https://www.acfun.cn/v/list110/index.htm"
    realmId:
      - "5" # 杂谈
      - "22" # 体育
      - "28" # 新闻资讯
      - "23" # 影视
