server:
  port: 5011
  host: localhost

database:
  host: localhost
  port: 5432
  username: postgres
  password: 1
  dbname: acfun_comm
  reservedConn: 10

logger:
  level: "debug"
  onSave: false
  path: "./logs/runlog.log"
  maxSize: 10 # single log file size 10Mb
  maxBackups: 10 # max number of log files
  maxAge: 7 # day

proxyServer:
  port: 5010
  host: "192.168.214.129"
  customProxy: "" # highest priority, for test

observers:
  "comments": # name is fixed
    prefix: "cob"
    spec: 2
    perArticleMinDelay: 3 # second
    perArticleMaxDelay: 5 # second
    perCommentsPageMinDelay: 2 # second
    perCommentsPageMaxDelay: 4 # second
    retryCount: 3
    retryInterval: 10 # second
  "articles": # name is fixed
    prefix: "aob"
    spec: 1
    idleTime: 10 # minute
    retryCount: 5
    retryInterval: 10 # second

articlesRequestUrl: "https://www.acfun.cn/rest/pc-direct/article/feed"

articleUrl:
  - referer: "https://www.acfun.cn/v/list110/index.htm"
    realmId:
      - "5" # 杂谈
      - "22" # 体育
      - "28" # 新闻资讯
      - "23" # 影视
    spec: 100
