package main

// Generated by https://quicktype.io

type CommentsJsonResponse struct {
	Result      int64              `json:"result"`
	CurPage     int64              `json:"curPage"`
	IsUp        bool               `json:"isUp"`
	TotalPage   int64              `json:"totalPage"`
	CommentsMap map[string]Comment `json:"commentsMap"`
	PageSize    int64              `json:"pageSize"`
	TotalCount  int64              `json:"totalCount"`
	CommentIDS  []int64            `json:"commentIds"`
}

type Comment struct {
	Content    string `json:"content"`
	SourceID   int64  `json:"sourceId"`
	IsDelete   bool   `json:"isDelete"`
	Cid        int64  `json:"cid"`
	UserID     int64  `json:"userId"`
	IsUpDelete bool   `json:"isUpDelete"`
	Floor      int64  `json:"floor"`
	QuoteID    int64  `json:"quoteId"`
	UserName   string `json:"userName"`
	IsUp       bool   `json:"isUp"`
	Timestamp  int64  `json:"timestamp"`
}
